# fly.toml app configuration file generated for gpt3-5-api on 2024-09-14T17:53:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gpt3-5-api'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
